//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
)

func main() {
	f, err := os.Open("tokens.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	out, err := os.Create("token_names_map.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen_token_names.go; DO NOT EDIT.")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "package digest")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "import \"fmt\"")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// tokenNameMap maps token IDs to their constant names")
	fmt.Fprintln(out, "var tokenNameMap = map[int]string{")

	re := regexp.MustCompile(`^\s+([A-Z_][A-Z0-9_]*)\s+=\s+(\d+)`)
	seen := make(map[string]bool)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		matches := re.FindStringSubmatch(line)
		if matches != nil {
			name := matches[1]
			val := matches[2]
			if !seen[val] {
				seen[val] = true
				fmt.Fprintf(out, "\t%s: %q,\n", val, name)
			}
		}
	}

	fmt.Fprintln(out, "}")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// TokenName returns the constant name for a token ID")
	fmt.Fprintln(out, "func TokenName(tok int) string {")
	fmt.Fprintln(out, "\tif name, ok := tokenNameMap[tok]; ok {")
	fmt.Fprintln(out, "\t\treturn name")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\tif tok > 0 && tok < 256 {")
	fmt.Fprintln(out, "\t\treturn string(rune(tok))")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn fmt.Sprintf(\"TOKEN_%d\", tok)")
	fmt.Fprintln(out, "}")
}
