package digest

// Token info overrides derived from sql/gen_lex_token.cc
// Generated by generate_token_info_overrides.py
func initTokenInfoOverrides() {
	TokenInfos[WITH_ROLLUP_SYM].String = "WITH ROLLUP"
	TokenInfos[NOT2_SYM].String = "!"
	TokenInfos[OR2_SYM].String = "||"
	TokenInfos[PARAM_MARKER].String = "?"
	TokenInfos[SET_VAR].String = ":="
	TokenInfos[UNDERSCORE_CHARSET].String = "(_charset)"
	TokenInfos[JSON_SEPARATOR_SYM].String = "->"
	TokenInfos[JSON_UNQUOTED_SEPARATOR_SYM].String = "->>"
	TokenInfos[BIN_NUM].String = "(bin)"
	TokenInfos[DECIMAL_NUM].String = "(decimal)"
	TokenInfos[FLOAT_NUM].String = "(float)"
	TokenInfos[HEX_NUM].String = "(hex)"
	TokenInfos[LEX_HOSTNAME].String = "(hostname)"
	TokenInfos[LONG_NUM].String = "(long)"
	TokenInfos[NUM].String = "(num)"
	TokenInfos[TEXT_STRING].String = "(text)"
	TokenInfos[NCHAR_STRING].String = "(nchar)"
	TokenInfos[ULONGLONG_NUM].String = "(ulonglong)"
	TokenInfos[IDENT].String = "(id)"
	TokenInfos[IDENT_QUOTED].String = "(id_quoted)"
	TokenInfos[TOK_GENERIC_VALUE].String = "?"
	TokenInfos[TOK_GENERIC_VALUE_LIST].String = "?, ..."
	TokenInfos[TOK_ROW_SINGLE_VALUE].String = "(?)"
	TokenInfos[TOK_ROW_SINGLE_VALUE_LIST].String = "(?) /* , ... */"
	TokenInfos[TOK_ROW_MULTIPLE_VALUE].String = "(...)"
	TokenInfos[TOK_ROW_MULTIPLE_VALUE_LIST].String = "(...) /* , ... */"
	TokenInfos[TOK_IN_GENERIC_VALUE_EXPRESSION].String = "IN (...)"
	TokenInfos[TOK_IDENT].String = "(tok_id)"
	TokenInfos[TOK_IDENT_AT].String = "(tok_id_at)"
	TokenInfos[TOK_BY_NUMERIC_COLUMN].String = "(by_num_col)"
	TokenInfos[TOK_UNUSED].String = "UNUSED"

	// MySQL only sets m_append_space = false for '@' token
	// See gen_lex_token.cc line 391: compiled_token_array[(int)'@'].m_append_space = false;
	TokenInfos['@'].AppendSpace = false

	// StartExpr tokens - these indicate a following +/- would be unary, not binary
	// See gen_lex_token.cc lines 402-440
	TokenInfos['('].StartExpr = true
	TokenInfos[','].StartExpr = true
	TokenInfos['='].StartExpr = true
	TokenInfos['~'].StartExpr = true
	TokenInfos['+'].StartExpr = true
	TokenInfos['-'].StartExpr = true
	TokenInfos['*'].StartExpr = true
	TokenInfos['/'].StartExpr = true
	TokenInfos['%'].StartExpr = true
	TokenInfos['^'].StartExpr = true
	TokenInfos['|'].StartExpr = true
	TokenInfos['&'].StartExpr = true
	TokenInfos[EQ].StartExpr = true
	TokenInfos[NE].StartExpr = true
	TokenInfos[LT].StartExpr = true
	TokenInfos[LE].StartExpr = true
	TokenInfos[GT_SYM].StartExpr = true
	TokenInfos[GE].StartExpr = true
	TokenInfos[EQUAL_SYM].StartExpr = true
	TokenInfos[AND_AND_SYM].StartExpr = true
	TokenInfos[OR_OR_SYM].StartExpr = true
	TokenInfos[AND_SYM].StartExpr = true
	TokenInfos[OR_SYM].StartExpr = true
	TokenInfos[OR2_SYM].StartExpr = true
	TokenInfos[XOR].StartExpr = true
	TokenInfos[NOT_SYM].StartExpr = true
	TokenInfos[BETWEEN_SYM].StartExpr = true
	TokenInfos[LIKE].StartExpr = true
	TokenInfos[REGEXP].StartExpr = true
	TokenInfos[SELECT_SYM].StartExpr = true
	TokenInfos[WHERE].StartExpr = true
	TokenInfos[HAVING].StartExpr = true
	TokenInfos[SET_SYM].StartExpr = true
	TokenInfos[VALUES].StartExpr = true
	TokenInfos[CASE_SYM].StartExpr = true
	TokenInfos[WHEN_SYM].StartExpr = true
	TokenInfos[THEN_SYM].StartExpr = true
	TokenInfos[ELSE].StartExpr = true
	TokenInfos[RETURN_SYM].StartExpr = true
	TokenInfos[IF].StartExpr = true
	TokenInfos[ELSEIF_SYM].StartExpr = true
	TokenInfos[WHILE_SYM].StartExpr = true
	TokenInfos[UNTIL_SYM].StartExpr = true
	TokenInfos[BY].StartExpr = true
	TokenInfos[LIMIT].StartExpr = true
	TokenInfos[OFFSET_SYM].StartExpr = true
	TokenInfos[AS].StartExpr = true
	TokenInfos[SHIFT_LEFT].StartExpr = true
	TokenInfos[SHIFT_RIGHT].StartExpr = true
	TokenInfos[INTERVAL_SYM].StartExpr = true
	TokenInfos[DIV_SYM].StartExpr = true
	TokenInfos[MOD_SYM].StartExpr = true
	TokenInfos[EVERY_SYM].StartExpr = true
	TokenInfos[AT_SYM].StartExpr = true
	TokenInfos[STARTS_SYM].StartExpr = true
	TokenInfos[ENDS_SYM].StartExpr = true
	TokenInfos[DEFAULT_SYM].StartExpr = true
	// IN_SYM is also a start_expr token (added for completeness)
	TokenInfos[IN_SYM].StartExpr = true

	// Hint comment tokens
	TokenInfos[TOK_HINT_COMMENT_OPEN].String = "/*+"
	TokenInfos[TOK_HINT_COMMENT_CLOSE].String = "*/"

	// Hintable statement tokens
	TokenInfos[SELECT_SYM].IsHintable = true
	TokenInfos[INSERT_SYM].IsHintable = true
	TokenInfos[UPDATE_SYM].IsHintable = true
	TokenInfos[DELETE_SYM].IsHintable = true
	TokenInfos[REPLACE_SYM].IsHintable = true
}
