import hashlib
from pathlib import Path
import re
import subprocess
import urllib.request

REVISION = "200daa1a93c5138d5843be35ace1e613b3aecc11"
SHA256 = "a1cf341bd39cf2798ebf60ba9e9c4252e47212a783256513291367a82c08b84b"
URL = f"https://raw.githubusercontent.com/mysql/mysql-server/{REVISION}/sql/lex.h"

with urllib.request.urlopen(URL, timeout=30) as response:
    source = response.read()
if hashlib.sha256(source).hexdigest() != SHA256:
    raise SystemExit("The upstream checksum does not match")

pairs = re.findall(
    r'SYM(?:_FN|_HK|_H)?\s*\(\s*"([^"]+)"\s*,\s*(\w+)\s*\)',
    source.decode(),
)
names = {token: name for name, token in pairs}
names["USER"] = "USER"
lines = [
    "// Code generated by scripts/generate_token_names.py; DO NOT EDIT.",
    f"// Source: {URL}",
    "",
    "package internal",
    "",
    "func init() {",
]
lines.extend(f'\tTokenInfos[{token}].String = "{name}"' for token, name in names.items())
lines.extend(["}", ""])
output = Path(__file__).resolve().parents[1] / "internal" / "token_names.go"
formatted = subprocess.run(
    ["gofmt"], input="\n".join(lines), text=True, capture_output=True, check=True
)
output.write_text(formatted.stdout)
